services:
  collector:
    build: 
      context: https://github.com/michaelzoellner/metering.git
      dockerfile: ./collector/Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ${PROJECT_DATA_PATH}:/data:ro
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data