# Version: 0.1.1
services:
  collector:
    image: ghcr.io/michaelzoellner/metering-collector:latest
    restart: always
    depends_on:
      - db
    volumes:
      - ${PROJECT_DATA_PATH}:/data:ro
    environment:
      - LOG_ALL_MQTT_DATA=${LOG_ALL_MQTT_DATA}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  metering-admin:
    image: ghcr.io/michaelzoellner/metering-admin:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${ADMIN_PORT:-8001}:8000"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data